### ISSUE TITLE
似乎不能使用GPU？

### ISSUE THREAD

**Issue by sojuo** [ssnangua/iyo-image-converter#1]
在进行图片压缩时GPU的占用似乎很小，而CPU的占用似乎很大
![Taskmgr_WoqZksdJlF](https://github.com/ssnangua/iyo-image-converter/assets/109811457/cc50dc35-4dde-44da-8da5-566d921445b9)
![Taskmgr_XZ1DyZXl4F](https://github.com/ssnangua/iyo-image-converter/assets/109811457/5949af8e-ebab-4615-98b5-8847c9c23cab)
鄙人不才，不是很懂GPU和CPU的功能，只知一般GPU在图形方面的工作优于CPU。但iyo似乎并未用到GPU。亦或是我设置有误？

**Comment by ssnangua** [comment]
本工具主要基于 [sharp](https://sharp.pixelplumbing.com/) 库，这个库应该是没有支持GPU的（见 [#1202](https://github.com/lovell/sharp/issues/1202)）
